// Generated by CoffeeScript 1.11.1
(function() {
  var http, user;

  http = require('http');

  user = require('./user');

  http.createServer(function(req, res) {
    user.get('Louis', function(id) {
      res.writeHead(200, {
        'Content-Type': 'text/plain'
      });
      res.end('hello ' + id);
    });
  }).listen(1337, '127.0.0.1');

}).call(this);
